// AUTO MAINTAINED FILE: DO NOT CHANGE

export const COUNTER_PLUS_ONE = 'COUNTER_PLUS_ONE';
export const COUNTER_MINUS_ONE = 'COUNTER_MINUS_ONE';
export const RESET_COUNTER = 'RESET_COUNTER';
export const FETCH_REDDIT_REACTJS_LIST_BEGIN = 'FETCH_REDDIT_REACTJS_LIST_BEGIN';
export const FETCH_REDDIT_REACTJS_LIST_SUCCESS = 'FETCH_REDDIT_REACTJS_LIST_SUCCESS';
export const FETCH_REDDIT_REACTJS_LIST_FAILURE = 'FETCH_REDDIT_REACTJS_LIST_FAILURE';
export const FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR = 'FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR';
export const HOME_FETCH_REDDIT_BY_SAGA_BEGIN = 'HOME_FETCH_REDDIT_BY_SAGA_BEGIN';
export const HOME_FETCH_REDDIT_BY_SAGA_SUCCESS = 'HOME_FETCH_REDDIT_BY_SAGA_SUCCESS';
export const HOME_FETCH_REDDIT_BY_SAGA_FAILURE = 'HOME_FETCH_REDDIT_BY_SAGA_FAILURE';
export const HOME_FETCH_REDDIT_BY_SAGA_DISMISS_ERROR = 'HOME_FETCH_REDDIT_BY_SAGA_DISMISS_ERROR';
