// AUTO MAINTAINED FILE: DO NOT CHANGE

export const HOME_COUNTER_PLUS_ONE = 'HOME_COUNTER_PLUS_ONE';
export const HOME_COUNTER_MINUS_ONE = 'HOME_COUNTER_MINUS_ONE';
export const HOME_RESET_COUNTER = 'HOME_RESET_COUNTER';
export const HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN = 'HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN';
export const HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS = 'HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS';
export const HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE = 'HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE';
export const HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR = 'HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR';
export const HOME_FETCH_REDDIT_BY_SAGA_BEGIN = 'HOME_FETCH_REDDIT_BY_SAGA_BEGIN';
export const HOME_FETCH_REDDIT_BY_SAGA_SUCCESS = 'HOME_FETCH_REDDIT_BY_SAGA_SUCCESS';
export const HOME_FETCH_REDDIT_BY_SAGA_FAILURE = 'HOME_FETCH_REDDIT_BY_SAGA_FAILURE';
export const HOME_FETCH_REDDIT_BY_SAGA_DISMISS_ERROR = 'HOME_FETCH_REDDIT_BY_SAGA_DISMISS_ERROR';
