export const PLUGIN_DEFAULT_LINT_BEGIN = 'PLUGIN_DEFAULT_LINT_BEGIN';
export const PLUGIN_DEFAULT_LINT_SUCCESS = 'PLUGIN_DEFAULT_LINT_SUCCESS';
export const PLUGIN_DEFAULT_LINT_FAILURE = 'PLUGIN_DEFAULT_LINT_FAILURE';
export const PLUGIN_DEFAULT_LINT_DISMISS_ERROR = 'PLUGIN_DEFAULT_LINT_DISMISS_ERROR';
export const PLUGIN_DEFAULT_SET_PROBLEMS = 'PLUGIN_DEFAULT_SET_PROBLEMS';
