export const COMMON_MY_SAGA_BEGIN = 'COMMON_MY_SAGA_BEGIN';
export const COMMON_MY_SAGA_SUCCESS = 'COMMON_MY_SAGA_SUCCESS';
export const COMMON_MY_SAGA_FAILURE = 'COMMON_MY_SAGA_FAILURE';
export const COMMON_MY_SAGA_DISMISS_ERROR = 'COMMON_MY_SAGA_DISMISS_ERROR';
