export const LAYOUT_A_1_BEGIN = 'LAYOUT_A_1_BEGIN';
export const LAYOUT_A_1_SUCCESS = 'LAYOUT_A_1_SUCCESS';
export const LAYOUT_A_1_FAILURE = 'LAYOUT_A_1_FAILURE';
export const LAYOUT_A_1_DISMISS_ERROR = 'LAYOUT_A_1_DISMISS_ERROR';
