export const TEST_2_TEST_ACTION = 'TEST_2_TEST_ACTION';
export const MY_ASYNC_ACTION_BEGIN = 'MY_ASYNC_ACTION_BEGIN';
export const MY_ASYNC_ACTION_SUCCESS = 'MY_ASYNC_ACTION_SUCCESS';
export const MY_ASYNC_ACTION_FAILURE = 'MY_ASYNC_ACTION_FAILURE';
export const MY_ASYNC_ACTION_DISMISS_ERROR = 'MY_ASYNC_ACTION_DISMISS_ERROR';
