export const CONFIG_FETCH_DEPS_BEGIN = 'CONFIG_FETCH_DEPS_BEGIN';
export const CONFIG_FETCH_DEPS_SUCCESS = 'CONFIG_FETCH_DEPS_SUCCESS';
export const CONFIG_FETCH_DEPS_FAILURE = 'CONFIG_FETCH_DEPS_FAILURE';
export const CONFIG_FETCH_DEPS_DISMISS_ERROR = 'CONFIG_FETCH_DEPS_DISMISS_ERROR';
export const CONFIG_INSTALL_PACKAGE_BEGIN = 'CONFIG_INSTALL_PACKAGE_BEGIN';
export const CONFIG_INSTALL_PACKAGE_SUCCESS = 'CONFIG_INSTALL_PACKAGE_SUCCESS';
export const CONFIG_INSTALL_PACKAGE_FAILURE = 'CONFIG_INSTALL_PACKAGE_FAILURE';
export const CONFIG_INSTALL_PACKAGE_DISMISS_ERROR = 'CONFIG_INSTALL_PACKAGE_DISMISS_ERROR';
