export const CONFIG_FETCH_DEPS_BEGIN = 'CONFIG_FETCH_DEPS_BEGIN';
export const CONFIG_FETCH_DEPS_SUCCESS = 'CONFIG_FETCH_DEPS_SUCCESS';
export const CONFIG_FETCH_DEPS_FAILURE = 'CONFIG_FETCH_DEPS_FAILURE';
export const CONFIG_FETCH_DEPS_DISMISS_ERROR = 'CONFIG_FETCH_DEPS_DISMISS_ERROR';
