export const REKIT_CMDS_SHOW_CMD_DIALOG = 'REKIT_CMDS_SHOW_CMD_DIALOG';
export const REKIT_CMDS_HIDE_CMD_DIALOG = 'REKIT_CMDS_HIDE_CMD_DIALOG';
export const REKIT_CMDS_EXEC_CMD_BEGIN = 'REKIT_CMDS_EXEC_CMD_BEGIN';
export const REKIT_CMDS_EXEC_CMD_SUCCESS = 'REKIT_CMDS_EXEC_CMD_SUCCESS';
export const REKIT_CMDS_EXEC_CMD_FAILURE = 'REKIT_CMDS_EXEC_CMD_FAILURE';
export const REKIT_CMDS_EXEC_CMD_DISMISS_ERROR = 'REKIT_CMDS_EXEC_CMD_DISMISS_ERROR';
