// AUTO MAINTAINED FILE: DO NOT CHANGE

export const COUNTER_PLUS_ONE = 'COUNTER_PLUS_ONE';
export const COUNTER_MINUS_ONE = 'COUNTER_MINUS_ONE';
export const RESET_COUNTER = 'RESET_COUNTER';
export const FETCH_REDDIT_REACTJS_LIST_BEGIN = 'FETCH_REDDIT_REACTJS_LIST_BEGIN';
export const FETCH_REDDIT_REACTJS_LIST_SUCCESS = 'FETCH_REDDIT_REACTJS_LIST_SUCCESS';
export const FETCH_REDDIT_REACTJS_LIST_FAILURE = 'FETCH_REDDIT_REACTJS_LIST_FAILURE';
export const FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR = 'FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR';
